// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class AnyMoveConditionIdWildcard {
    @JsonValue
    private String value;

    public AnyMoveConditionIdWildcard() {
    }

    @JsonCreator
    public AnyMoveConditionIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
