// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class AnyMoveOutcomeIdWildcard {
    @JsonValue
    private String value;

    public AnyMoveOutcomeIdWildcard() {
    }

    @JsonCreator
    public AnyMoveOutcomeIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
