// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded AssetAbilityMoveOutcomeId that can be used to match multiple
 * AssetAbilityMoveOutcome objects.
 */
public class AssetAbilityMoveOutcomeIdWildcard {
    @JsonValue
    private String value;

    public AssetAbilityMoveOutcomeIdWildcard() {
    }

    @JsonCreator
    public AssetAbilityMoveOutcomeIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
