// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded MoveConditionId that can be used to match multiple MoveCondition
 * objects.
 */
public class MoveConditionIdWildcard {
    @JsonValue
    private String value;

    public MoveConditionIdWildcard() {
    }

    @JsonCreator
    public MoveConditionIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
