// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded MoveOutcomeId that can be used to match multiple MoveOutcome
 * objects.
 */
public class MoveOutcomeIdWildcard {
    @JsonValue
    private String value;

    public MoveOutcomeIdWildcard() {
    }

    @JsonCreator
    public MoveOutcomeIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
