// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum TaggableNodeType {
    @JsonProperty("ability")
    ABILITY,

    @JsonProperty("asset")
    ASSET,

    @JsonProperty("asset_collection")
    ASSET_COLLECTION,

    @JsonProperty("atlas_collection")
    ATLAS_COLLECTION,

    @JsonProperty("atlas_entry")
    ATLAS_ENTRY,

    @JsonProperty("condition")
    CONDITION,

    @JsonProperty("condition_meter")
    CONDITION_METER,

    @JsonProperty("danger")
    DANGER,

    @JsonProperty("delve_site")
    DELVE_SITE,

    @JsonProperty("delve_site_domain")
    DELVE_SITE_DOMAIN,

    @JsonProperty("delve_site_theme")
    DELVE_SITE_THEME,

    @JsonProperty("denizen")
    DENIZEN,

    @JsonProperty("feature")
    FEATURE,

    @JsonProperty("impact")
    IMPACT,

    @JsonProperty("move")
    MOVE,

    @JsonProperty("move_category")
    MOVE_CATEGORY,

    @JsonProperty("npc")
    NPC,

    @JsonProperty("npc_collection")
    NPC_COLLECTION,

    @JsonProperty("option")
    OPTION,

    @JsonProperty("oracle_collection")
    ORACLE_COLLECTION,

    @JsonProperty("oracle_rollable")
    ORACLE_ROLLABLE,

    @JsonProperty("outcome")
    OUTCOME,

    @JsonProperty("rarity")
    RARITY,

    @JsonProperty("row")
    ROW,

    @JsonProperty("special_track")
    SPECIAL_TRACK,

    @JsonProperty("stat")
    STAT,

    @JsonProperty("truth")
    TRUTH,

    @JsonProperty("variant")
    VARIANT,
}
