// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

/**
 * Describes changes/additions made to the enhanced move's trigger conditions.
 */
@JsonSerialize
public class TriggerNoRollEnhancement {
    @JsonProperty("conditions")
    private List<TriggerNoRollConditionEnhancement> conditions;

    public TriggerNoRollEnhancement() {
    }

    /**
     * Getter for conditions.<p>
     * Trigger conditions added to the enhanced move.
     */
    public List<TriggerNoRollConditionEnhancement> getConditions() {
        return conditions;
    }

    /**
     * Setter for conditions.<p>
     * Trigger conditions added to the enhanced move.
     */
    public void setConditions(List<TriggerNoRollConditionEnhancement> conditions) {
        this.conditions = conditions;
    }
}
