// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded AssetAbilityMoveOutcomeId that can be used to match
    /// multiple AssetAbilityMoveOutcome objects.
    /// </summary>
    [JsonConverter(typeof(AssetAbilityMoveOutcomeIdWildcardJsonConverter))]
    public class AssetAbilityMoveOutcomeIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class AssetAbilityMoveOutcomeIdWildcardJsonConverter : JsonConverter<AssetAbilityMoveOutcomeIdWildcard>
    {
        public override AssetAbilityMoveOutcomeIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new AssetAbilityMoveOutcomeIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, AssetAbilityMoveOutcomeIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
