// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded AssetAbilityMoveConditionId that can be used to match
    /// multiple AssetAbilityMoveCondition objects.
    /// </summary>
    [JsonConverter(typeof(AssetAbilityMoveConditionIdWildcardJsonConverter))]
    public class AssetAbilityMoveConditionIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class AssetAbilityMoveConditionIdWildcardJsonConverter : JsonConverter<AssetAbilityMoveConditionIdWildcard>
    {
        public override AssetAbilityMoveConditionIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new AssetAbilityMoveConditionIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, AssetAbilityMoveConditionIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
