// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A unique ID representing an AssetAbilityMoveCondition object.
    /// </summary>
    [JsonConverter(typeof(AssetAbilityMoveConditionIdJsonConverter))]
    public class AssetAbilityMoveConditionId
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class AssetAbilityMoveConditionIdJsonConverter : JsonConverter<AssetAbilityMoveConditionId>
    {
        public override AssetAbilityMoveConditionId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new AssetAbilityMoveConditionId { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, AssetAbilityMoveConditionId value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
