// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded MoveOutcomeId that can be used to match multiple
    /// MoveOutcome objects.
    /// </summary>
    [JsonConverter(typeof(MoveOutcomeIdWildcardJsonConverter))]
    public class MoveOutcomeIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class MoveOutcomeIdWildcardJsonConverter : JsonConverter<MoveOutcomeIdWildcard>
    {
        public override MoveOutcomeIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new MoveOutcomeIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, MoveOutcomeIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
