// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// A wildcarded MoveConditionId that can be used to match multiple
    /// MoveCondition objects.
    /// </summary>
    [JsonConverter(typeof(MoveConditionIdWildcardJsonConverter))]
    public class MoveConditionIdWildcard
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class MoveConditionIdWildcardJsonConverter : JsonConverter<MoveConditionIdWildcard>
    {
        public override MoveConditionIdWildcard Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new MoveConditionIdWildcard { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, MoveConditionIdWildcard value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
